In [1]:
import numpy as np
from scipy.linalg import lu

### Solve the following system of equations using LU Decomposition method:
#### Find L and U by hand.
#### Confirm that A=LU then solve.
- Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.
- Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

#### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

### Note (when using scipy):
- In the second system of equations We can see the <b>L and U</b> we get are different from the ones we got by hand. 
- You will also see there is a permutation matrix <b>P</b> that returned by the <b>lu function</b>. 
- This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). 
- If you multiply <b>P with A</b>, you will see that this permutation matrix effect.
- You will need to arrange the ouput based on the new matrix <b>A</b> achieved by <b>LU</b> multiplication in order to correctly solve the system of equations.

In [2]:
A = np.array([[2, 5], [1, 2]])
A

array([[2, 5],
       [1, 2]])

In [3]:
Y = np.array([[21], [8]])
Y

array([[21],
       [ 8]])

In [4]:
P, L, U = lu(A)
print("P:\n", P, "\nL:\n", L, "\nU:\n", U)

P:
 [[1. 0.]
 [0. 1.]] 
L:
 [[1.  0. ]
 [0.5 1. ]] 
U:
 [[ 2.   5. ]
 [ 0.  -0.5]]


In [5]:
# L = np.tril(A)
# L

In [6]:
# U = np.triu(A)
# U

In [7]:
M = np.linalg.inv(L) @ Y
M

array([[21. ],
       [-2.5]])

In [8]:
X = np.linalg.inv(U) @ M
X

array([[-2.],
       [ 5.]])

In [9]:
A = np.array([[1, 1, 1], [4, 3, -1], [3, 5, 3]])
A

array([[ 1,  1,  1],
       [ 4,  3, -1],
       [ 3,  5,  3]])

In [10]:
Y = np.array([[1], [6], [4]])
Y

array([[1],
       [6],
       [4]])

In [11]:
P, L, U = lu(A)
print("P:\n", P, "\nL:\n", L, "\nU:\n", U)

P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] 
L:
 [[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]] 
U:
 [[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]


In [12]:
# As Matrix(P) is not an identity matrix
# So we compute matrix(Y) as:
Y = np.linalg.inv(P) @ Y
Y

array([[6.],
       [4.],
       [1.]])

In [13]:
M = np.linalg.inv(L) @ Y
M

array([[ 6.        ],
       [-0.5       ],
       [-0.45454545]])

In [14]:
X = np.linalg.inv(U) @ M
X

array([[ 1. ],
       [ 0.5],
       [-0.5]])

### Apply the Jacobi and Gauss-Seidel method to solve
- 𝟓𝒙𝟏−𝟐𝒙𝟐+𝟑𝒙𝟑=−𝟏, −𝟑𝒙𝟏+𝟗𝒙𝟐+𝒙𝟑=𝟐, 𝟐𝒙𝟏−𝒙𝟐−𝟕𝒙𝟑=𝟑
- Solve once without vectorization then use vectorize implementation.
- Check for convergance.
- Use different tolerence and see the difference between the two methods. e.g. tol: 0.01,0.001,0.0001 ... etc.

diagonal    : [5 9 7]
off diagonal: [5 4 3]
matrix is diagonally dominant


# Jacobi

In [ ]:
X1, X2, X3 = 0, 0, 0
for i in range(10):
    X = np.array([[(2*X2 - 3*X3 - 1) / 5], [(3*X1 - X3 + 2) / 9], [(2*X1 - X2 -3) / 7]])
    X1, X2, X3 = X[0], X[1], X[2]
    print("Iter #{}".format(i+1), X.reshape(1, 3))

Iter #1 [[-0.2         0.22222222 -0.42857143]]
Iter #2 [[ 0.14603175  0.2031746  -0.51746032]]
Iter #3 [[ 0.19174603  0.32839506 -0.41587302]]
Iter #4 [[ 0.18088183  0.33234568 -0.42070043]]
Iter #5 [[ 0.18535853  0.32926066 -0.42436886]]
Iter #6 [[ 0.18632558  0.33116049 -0.42264909]]
Iter #7 [[ 0.18605365  0.33129176 -0.42264419]]
Iter #8 [[ 0.18610322  0.33120057 -0.42274064]]
Iter #9 [[ 0.18612461  0.33122781 -0.42271345]]
Iter #10 [[ 0.18611919  0.33123192 -0.42271123]]


In [ ]:
f1 = lambda x1,x2,x3: (2*x2 - 3*x3 - 1) / 5
f2 = lambda x1,x2,x3: (3*x1 - x3 + 2) / 9
f3 = lambda x1,x2,x3: (2*x1 - x2 -3) / 7

x01, x02, x03 = 0, 0, 0
i = 0
print("Iteration\t\tX1\t\t\t\tX2\t\t\t\tX3")

while i<10:
    x1 = f1(x01,x02,x03)
    x2 = f2(x01,x02,x03)
    x3 = f3(x01,x02,x03)
    i+=1
    print(i, "\t\t", x1, "\t\t", x2, "\t\t", x3)
    x01, x02, x03 = x1, x2, x3

Iteration		X1				X2				X3
1 		 -0.2 		 0.2222222222222222 		 -0.42857142857142855
2 		 0.146031746031746 		 0.20317460317460317 		 -0.5174603174603175
3 		 0.19174603174603178 		 0.32839506172839505 		 -0.41587301587301584
4 		 0.18088183421516754 		 0.3323456790123457 		 -0.42070042831947596
5 		 0.18535852859662386 		 0.3292606589961087 		 -0.42436885865457297
6 		 0.18632557879118722 		 0.3311604938271605 		 -0.4226490859718373
7 		 0.1860536491139666 		 0.3312917580383777 		 -0.4226441908921123
8 		 0.18610321775061847 		 0.3312005709148902 		 -0.42274063711577775
9 		 0.1861246106354227 		 0.3312278100408481 		 -0.42271344791623616
10 		 0.18611919276608094 		 0.33123191998027823 		 -0.42271122696714325


- Vectorized Implementation

In [ ]:
def Jacobi(A, B, X, n, epsilon):
    # A decomposed into a diagonal component D, a lower triangular part L and an upper triangular part U --> A = D + L + U
    # Get diagonal elements
    D = np.diag(A)
    # R = L + U (Off-diagonal parts)
    R = A - np.diag(D)
    X_old = X

    for i in range(n):
        X_new = np.linalg.inv(np.diag(D)) @ (B - R @ X_old)
        if (np.linalg.norm(X_new - X_old, ord=np.inf) < epsilon):
            print("No. of Iterations:", i+1)
            break;
        X_old = X_new
    return X_new

In [ ]:
X = np.zeros(3).reshape(-1, 1)
A = np.array([[5, -2, 3], [-3, 9, 1], [2, -1, -7]])
B = np.array([[-1], [2], [3]])
Jacobi(A, B, X, 20, 0.00001)

No. of Iterations: 10


array([[ 0.18611919],
       [ 0.33123192],
       [-0.42271123]])

# Gauss_Seidel

- Vectorized Implementation

In [ ]:
def Gauss_Seidel(A, B, X, n, epsilon):
    # A decomposed into a lower triangular component L*, and a strictly upper triangular component U --> A = L* + U
    # Get L*
    L = np.tril(A)
    # Get U
    U = np.triu(A) - np.diag(np.diag(A))
    X_old = X

    for i in range(n):
        X_new = np.linalg.inv(L) @ (B - U @ X_old)
        if (np.linalg.norm(X_new - X_old, ord=np.inf) < epsilon):
            print("No. of Iterations:", i+1)
            break;
        X_old = X_new
    return X_new

In [ ]:
X = np.zeros(3).reshape(-1, 1)
A = np.array([[5, -2, 3], [-3, 9, 1], [2, -1, -7]])
B = np.array([[-1], [2], [3]])
Gauss_Seidel(A, B, X, 20, 0.00001)

No. of Iterations: 7


array([[ 0.1861206 ],
       [ 0.33123065],
       [-0.42271278]])

### Use np.linalg.solve() to solve the previous system and compare the results.

In [15]:
a = np.array([[5, -2, 3], [-3, 9, 1], [2, -1, -7]])
b = np.array([[-1], [2], [3]])
np.linalg.solve(a, b)

array([[ 0.18611987],
       [ 0.33123028],
       [-0.42271293]])

### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

In [16]:
P, L, U = lu(a)
print("P:\n", P, "\nL:\n", L, "\nU:\n", U)

P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
L:
 [[ 1.          0.          0.        ]
 [-0.6         1.          0.        ]
 [ 0.4        -0.02564103  1.        ]] 
U:
 [[ 5.         -2.          3.        ]
 [ 0.          7.8         2.8       ]
 [ 0.          0.         -8.12820513]]


In [18]:
M = np.linalg.inv(L) @ b
X = np.linalg.inv(U) @ M
print("a =", a, "\nLU =", L @ U, "\nM =", M, "\n\nSolution:\nX =",X)

a = [[ 5 -2  3]
 [-3  9  1]
 [ 2 -1 -7]] 
LU = [[ 5. -2.  3.]
 [-3.  9.  1.]
 [ 2. -1. -7.]] 
M = [[-1.        ]
 [ 1.4       ]
 [ 3.43589744]] 

Solution:
X = [[ 0.18611987]
 [ 0.33123028]
 [-0.42271293]]
